export const BUSINESS_UNIT = [
    { 
        id: 1,
        name: "Sabika Arabindo",
        logo: "/bisnis/1.png",
        image: "https://images.pexels.com/photos/6195284/pexels-photo-6195284.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        link: "https://www.sabikaarabindo.com",
        desc: "Worker Provider", 
    },
    { 
        id: 2,
        name: "Sabika Propertindo", 
        logo: "/bisnis/2.png",
        image: "https://images.pexels.com/photos/271639/pexels-photo-271639.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        link: "https://www.ustayhotels.com",
        desc: "Hotels & Property", 
    },
    { 
        id: 3, 
        name: "Sabika Al-Haramain", 
        logo: "/bisnis/3.png",
        image: "https://images.pexels.com/photos/30636370/pexels-photo-30636370/free-photo-of-group-of-pilgrims-in-saudi-arabian-street-gathering.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        link: "https://www.alharamain.com",
        desc: "Travel & Umroh", 
    },
    { 
        id: 4,
        name: "Sabika Media Management",
        logo: "/bisnis/4.png",
        image: "https://images.pexels.com/photos/6476256/pexels-photo-6476256.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1", 
        link: "https://www.expkreativ.id",
        desc: "360 Digital Agency", 
    },
    { 
        id: 5,
        name: "Sabika Otomotif", 
        logo: "/bisnis/5.png",
        image: "https://images.pexels.com/photos/164634/pexels-photo-164634.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        link: "https://www.expkreativ.id",
        desc: "Buy & Sell Cars", 
    },
    { 
        id: 6,
        name: "Sabika Mitra Kontruksi", 
        logo: "/bisnis/6.png",
        image: "https://images.pexels.com/photos/439416/pexels-photo-439416.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
        link: "https://www.expkreativ.id",
        desc: "Contractor & General Suppliers", 
    },
    { 
        id: 7,
        name: "Sabika Pangan Nusantara", 
        logo: "/bisnis/7.png",
        image: "https://images.pexels.com/photos/2074130/pexels-photo-2074130.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
        link: "https://www.expkreativ.id",
        desc: "Food & Beverages", 
    },
    { 
        id: 8,
        name: "Sabika Global Informatika",
        logo: "/bisnis/8.png", 
        image: "https://images.pexels.com/photos/546819/pexels-photo-546819.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
        link: "https://www.expkreativ.id",
        desc: "IT Solutions", 
    },
    { 
        id: 9,
        name: "Sabika Putra Perkasa Energi", 
        logo: "/bisnis/9.png",
        image: "https://images.pexels.com/photos/2101137/pexels-photo-2101137.jpeg?_gl=1*8uplo9*_ga*ODY1OTg2Nzk1LjE3MzkyMDU1NDU.*_ga_8JE65Q40S6*czE3NTAzMjQ0NTAkbzMkZzEkdDE3NTAzMjQ0OTIkajE4JGwwJGgw",
        link: "https://www.expkreativ.id",
        desc: "Resources & Energy", 
    },
    { 
        id: 10,
        name: "U Stay", 
        logo: "/bisnis/10.png",
        image: "https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg?_gl=1*1yuxjdf*_ga*ODY1OTg2Nzk1LjE3MzkyMDU1NDU.*_ga_8JE65Q40S6*czE3NTAzMjQ0NTAkbzMkZzEkdDE3NTAzMjQ1MTYkajU5JGwwJGgw",
        link: "https://www.expkreativ.id",
        desc: "Hospitality Management", 
    },
    { 
        id: 11,
        name: "Satria Birawa Security", 
        logo: "/bisnis/11.png",
        image: "https://images.pexels.com/photos/7714754/pexels-photo-7714754.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
        link: "https://www.expkreativ.id",
        desc: "Outsorcing & Security Services", 
    },
];

export const NETWORK_STORIES = [
    { 
        id: 1,
        name: "Sandiaga Uno",
        image: "/SU.png",
        text: "Sabika Group’s commitment to excellence and innovation is unparalleled. Nofel’s leadership has been instrumental in creating opportunities that uplift industries.", 
    },
    { 
        id: 2,
        name: "Raffi Ahmad", 
        image: "/RA.png",
        text: "It’s been an honor to collaborate with Sabika Group. Their passion for progress and sustainable business. I look forward to continuing our partnership.", 
    },
    { 
        id: 3, 
        name: "Baim Wong", 
        image: "/BW.png",
        text: "Sabika Group’s dedication to creating meaningful ventures and collaborations is truly inspiring. It’s been a pleasure to work alongside Nofel and his team.", 
    },
];
  
  